# Generated by Django 4.1.3 on 2022-12-24 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plugins.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=plugins.models.tz_now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=1)),
                ('title', models.CharField(db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
