# Generated by Django 4.1.3 on 2022-12-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default=1, max_length=1, verbose_name=((1, 'Open'), (2, 'Close'))),
        ),
    ]
